author: Johan Piña & Santiago Barrero
logo: _static/logosem.png
copyright: "2026"
title: Curso de Programación I

execute:
  execute_notebooks: off

exclude_patterns:
  - "node_modules/**"
  - "**/node_modules/**"
  - ".venv/**"
  - "**/.ipynb_checkpoints/**"

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/BioAITeamLearning/AlgProgI_2026_02_Ucaldas
  branch: main

html:
  use_issues_button: false
  use_repository_button: false

launch_buttons:
  colab_url: "https://colab.research.google.com"

parse:
  myst_enable_extensions:
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    - html_admonition
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context

sphinx:
  config:
    language: es